@url = http://3.129.73.57:8080/api/event

@token = 

GET {{url}}/1 HTTP/1.1
Authorization: Bearer {{token}}

###

GET {{url}}/user/2 HTTP/1.1
Authorization: Bearer {{token}}

###

POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "eventName": "http test",
    "eventType": false,
    "startDate": "http test",
    "endDate": "false",
    "appUserId": 2,
    "startLocationId": 2,
    "endLocationId": 3
}

###

PUT {{url}}/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "eventId": 1,
    "eventName": 3,
    "eventName": "http update",
    "eventType": false,
    "startDate": "http update",
    "endDate": "update",
    "appUserId": 2,
    "startLocationId": 2,
    "endLocationId": 3
}

###

DELETE {{url}}/3 HTTP/1.1
Authorization: Bearer {{token}}
