
@url = http://localhost:8080/api/todo

# @url = http://3.129.73.57:8080/api/todo
@token = 

GET {{url}}/1 HTTP/1.1
Authorization: Bearer {{token}}

###

GET {{url}}/event/1 HTTP/1.1
Authorization: Bearer {{token}}

###

POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
{
    "toDoDate": "http test",
    "toDoName": "http test",
    "toDoDescription": "http test",
    "toDoStatus": false,
    "eventId": 2
}

###

PUT {{url}}/4 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "toDoId": 4,
    "toDoDate": "http update",
    "toDoName": "http update",
    "toDoDescription": "http update",
    "toDoStatus": false,
    "eventId": 2
}

###

DELETE {{url}}/3 HTTP/1.1
Authorization: Bearer {{token}}
