@url = http://localhost:8080/api/container

@token =

GET {{url}} HTTP/1.1
Authorization: Bearer {{token}}

###
GET {{url}}/1 HTTP/1.1
Authorization: Bearer {{token}}

###

GET {{url}}/event/1 HTTP/1.1
Authorization: Bearer {{token}}

###
POST {{url}} HTTP/1.1
Content-Type: application/application/json
Authorization: Bearer {{token}}

{
    "parentContainerId" : 1,
    "containerName": "test name",
    "eventId": 3
}

###
PUT {{url}}/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{   
    "containerId": 2,
    "parentContainerId" : 1,
    "containerName": "update name",
    "eventId": 3
}

###
DELETE {{url}}/2 HTTP/1.1
Authorization: Bearer{{token}}